apiVersion: v1
data:
  default.conf: |
    server {
      listen 8080;

      error_log  /var/log/nginx/error.log;

      location /api/v1/movies {
        proxy_pass http://movie:8001/api/v1/movies;
      }

      location /api/v1/casts {
        proxy_pass http://cast:8002/api/v1/casts;
      }

    }
kind: ConfigMap
metadata:
  name: nginx-configmap


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: nginx-configmap-vol
      volumes:
        - configMap:
            name: nginx-configmap
          name: nginx-configmap-vol

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - port: 8081
    targetPort: 8080
  type: LoadBalancer
