

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume-movie
  labels:
    type: local
    app: postgres-movie
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresqlmovie

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim-movie
  labels:
    app: postgres-movie
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret-movie
  labels:
    app: postgres-movie
data:
  POSTGRES_DB: movie_db_dev
  POSTGRES_USER: movie_db_username
  POSTGRES_PASSWORD: movie_db_password

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-movie-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-movie
  template:
    metadata:
      labels:
        app: postgres-movie
    spec:
      containers:
        - name: postgres-movie
          image: 'postgres:12.1-alpine'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret-movie
          volumeMounts:
            - mountPath: /var/lib/postgres/data
              name: postgresdatamovie
      volumes:
        - name: postgresdatamovie
          persistentVolumeClaim:
            claimName: postgres-volume-claim-movie

---

apiVersion: v1
kind: Service
metadata:
  name: moviedb
spec:
  selector:
    app: postgres-movie
  type: ClusterIP
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
