apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-api
  template:
    metadata:
      labels:
        app: cast-api
    spec:
      containers:
      - name: cast-api
        image: nguray/cast:latest
        command: ["uvicorn"]
        args: [ "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: cast
spec:
  selector:
    app: cast-api
  type: ClusterIP
  ports:
  - port: 8002
    protocol: TCP
    targetPort: 8000
