
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-secret-credentials-cast
  labels:
    app: postgresdbcast
data:
  POSTGRES_DB: cast_db_dev
  POSTGRES_USER: cast_db_username
  POSTGRES_PASSWORD: cast_db_password

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresdb-persistent-volume-cast-qa
  labels:
    type: local
    app: postgresdbcast
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/dbcast"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-persistent-volume-claim-qa
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdbcast
  template:
    metadata:
      labels:
        app: postgresdbcast
    spec:
      containers:
        - name: postgresdbcast
          image: postgres:12.1-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: db-secret-credentials-cast
          volumeMounts:
            - mountPath: /var/lib/postgres/data
              name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-persistent-volume-claim-qa


---

apiVersion: v1
kind: Service
metadata:
  name: castdb
spec:
  selector:
    app: postgresdbcast
  type: ClusterIP
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432

