apiVersion: v1
kind: ConfigMap
metadata:
  name: db-secret-credentials-movie
  labels:
    app: postgresdbmovie
data:
  POSTGRES_DB: movie_db_{STAGE}
  POSTGRES_USER: movie_db_username
  POSTGRES_PASSWORD: movie_db_password

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresdb-persistent-volume-movie-{STAGE}
  labels:
    type: local
    app: postgresdbmovie
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/dbmovie{STAGE}"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-persistent-volume-claim-movie-{STAGE}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdbmovie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdbmovie
  template:
    metadata:
      labels:
        app: postgresdbmovie
    spec:
      containers:
        - name: postgresdbmovie
          image: postgres:12.1-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: db-secret-credentials-movie
          volumeMounts:
            - mountPath: /var/lib/postgres/data
              name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-persistent-volume-claim-movie-{STAGE}


---

apiVersion: v1
kind: Service
metadata:
  name: moviedb
spec:
  selector:
    app: postgresdbmovie
  type: ClusterIP
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
