
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-secret-credentials1
  labels:
    app: postgresdb1
data:
  POSTGRES_DB: movie_db_dev
  POSTGRES_USER: movie_db_username
  POSTGRES_PASSWORD: movie_db_password

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresdb-persistent-volume1
  labels:
    type: local
    app: postgresdb1
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/db1"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-persistent-volume-claim1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb1
  template:
    metadata:
      labels:
        app: postgresdb1
    spec:
      containers:
        - name: postgresdb1
          image: postgres:12.1-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: db-secret-credentials1
          volumeMounts:
            - mountPath: /var/lib/postgres/data
              name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-persistent-volume-claim1


---

apiVersion: v1
kind: Service
metadata:
  name: moviedb
spec:
  selector:
    app: postgresdb1
  type: ClusterIP
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
